language: node_js
node_js:
  - "lts/*"

services:
  - docker

install:
  - npm install

after_success:
  - docker build -t achorein/game-keeper .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push achorein/game-keeper

deploy:
  provider: azure_web_apps
  verbose: true
